easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

homepage:
    path:      /
    defaults:  { _controller: AppBundle:Main:homepage }

music:
    path:      /music
    defaults:  { _controller: AppBundle:Main:music }

videos:
    path:      /videos
    defaults:  { _controller: AppBundle:Main:videos }

concerts:
    path:      /concerts
    defaults:  { _controller: AppBundle:Main:concerts }

photos:
    path:      /photos
    defaults:  { _controller: AppBundle:Main:photos }

download_img:
    path:      /download-img
    defaults:  { _controller: AppBundle:Main:downloadImg }

band:
    path:      /band
    defaults:  { _controller: AppBundle:Main:band }

contact:
    path:      /contact
    defaults:  { _controller: AppBundle:Main:contact }

issuu:
    path:      /issuu
    defaults:  { _controller: AppBundle:Main:issuu }

mailing_list:
    path:      /mailing-list
    defaults:  { _controller: AppBundle:Main:mailingList }