services:
    rootdiamoons_web.manager.concert:
        class: AppBundle\Manager\ConcertManager
        arguments:
            - @doctrine.orm.entity_manager
            - AppBundle\Entity\Concert

    rootdiamoons_web.manager.recop:
        class: AppBundle\Manager\RecopManager

    rootdiamoons_web.manager.subscribe:
        class: AppBundle\Manager\SubscribeManager
        arguments:
            - @mailer
            - @logger
            -
                - %subscribe_address%
                - %info_address%
            -
                - %unsubscribe_address%
                - %info_address%