# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    rootdiamoons_web.manager.concert:
        class: AppBundle\Manager\ConcertManager
        arguments:
            - @doctrine.orm.entity_manager
            - AppBundle\Entity\Concert

    rootdiamoons_web.manager.recop:
        class: AppBundle\Manager\RecopManager