AppBundle\Entity\Concert:
    properties:
        data:
            - NotBlank: ~
        concertCat:
            - NotBlank: ~
        concertCas:
            - NotBlank: ~
        concertEng:
            - NotBlank: ~
        lloc:
            - NotBlank: ~
        ciutat:
            - NotBlank: ~
        adreca:
            - NotBlank: ~
        preu:
            - NotBlank: ~
        textCat:
            - NotBlank: ~
        textCas:
            - NotBlank: ~
        textEng:
            - NotBlank: ~