App\Entity\Concert:
    type: entity
    repositoryClass: App\Repository\ConcertRepository
    table: concerts
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        data:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        concertCat:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: concert_cat
        concertCas:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: concert_cas
        concertEng:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: concert_eng
        lloc:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        ciutat:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        adreca:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: ''
        grups:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
        preu:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        preuAnticipada:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: preu_anticipada
        comprar:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        arribar:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
        mapa:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
        cartellNom:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: cartell_nom
        cartellTipus:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: cartell_tipus
        cartellMida:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: cartell_mida
        textCat:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: ''
            column: text_cat
        textCas:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: ''
            column: text_cas
        textEng:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: ''
            column: text_eng
        facebook:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        cancelat:
            type: boolean
            nullable: false
            comment: ''
            options:
                default: false
    lifecycleCallbacks: {  }
