App\Entity\User:
    type: entity
    table: users
    uniqueConstraints:
        username:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 40
            fixed: true
            comment: ''
        salt:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
